language: ruby
rvm:
  # Encoding does not exist in 1.8.7
  # No ruby-head as it is unstable
  # No Rubinius as it requires extra setup and is not supported yet
  # No jRuby as it depends on native C extensions
  # MRI
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
